### ISSUE TITLE
_AMM_ModScript_Manager defaults to CombinedModType 3 

### ISSUE THREAD

**Issue by 0ptera** [HolterPhylo/AMUMSS#15]
Since yesterdays update _AMM_ModScript_Manager defaults to naming combined mods COMPOSITE-NAME COMBINED MOD PAK like Mod1+Mod2+Mod3.pak instead of asking.

It also ignores CombinedModType setting in BUILDMOD_AUTO.bat

**Comment by HolterPhylo** [comment]
hmm, I guess you mean AMUMSS, because AMM does not create mod paks.

What version of AMUMSS?
When using AMM, is Auto checked?
- if Yes, you are using BUILMOD_AUTO.bat, CombinedModType 3 (create a COMPOSITE name)
- if No, you are using BUILDMOD.bat which default to CombinedModType ASK

I do not see the behavior you are describing, if I understand correctly.

I would suggest you come to [amumss-lua Discord channel](https://discord.com/channels/215514623384748034/657304493767262218)
It would be easier to help you in real time...

I believe this is a valid invite: [Invite](https://discord.gg/HFjnmnwe67)

**Comment by 0ptera** [comment]
I've been using ModScriptManager to start the batch jobs.
![grafik](https://github.com/HolterPhylo/AMUMSS/assets/8436934/df817cc5-16c7-41ab-9137-99db3ff28d43)

using BUILDMOD_AUTO.bat -CombinedModType 2 is ignored
using BUILDMOD.bat it doesn't ask 

only happens since the most recent update to the manager that also added all those neon colors.

**Comment by HolterPhylo** [comment]
Beside that AMM is v1.3.3.0, you did not give me more info...
I cannot duplicate your problem as my AMUMSS 4.3.0.0 install does not exhibit that behavior and works correctly.

AGAIN, please come to Discord if you want this resolved in a timely manner, otherwise it will take forever for us to exchange info in this issue

I would suggest you come to [amumss-lua Discord channel](https://discord.com/channels/215514623384748034/657304493767262218)
It would be easier to help you in real time...

I believe this is a valid invite: [Invite](https://discord.gg/HFjnmnwe67)

**Comment by 0ptera** [comment]
Will do, thanks.

**Comment by HolterPhylo** [comment]
I am there at the moment
